export default {
  showFooter: true,
  isSidebarCompact: true,
  showBreadcrumb: false,
  mode: "light",
  layout: "side",
  splitMenu: false,
  sideMode: "light",
  isFooterAside: false,
  isSidebarFixed: true,
  isHeaderFixed: true,
  isUseTabsRouter: false,
  showHeader: true,
  brandTheme: "#0052D9",
};